# action.yml
name: '.NetFramework Action Template'
description: 'Template for .Net Framework Action'
author: 'Gumpanat Keardkeawfa <https://github.com/Christopherchris>'
branding:
  icon: 'book-open'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
